export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAIL = 'AUTH_LOGIN_FAIL';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_LOGOUT_FAIL = 'AUTH_LOGOUT_FAIL';

export const AUTH_SIGNUP = 'AUTH_SIGNUP';
export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS';
export const AUTH_SIGNUP_FAIL = 'AUTH_SIGNUP_FAIL';

export const ADMIN_LOAD_DONORS = 'ADMIN_LOAD_DONORS';
export const ADMIN_LOAD_DONORS_SUCCESS = 'ADMIN_LOAD_DONORS_SUCCESS';
export const ADMIN_LOAD_DONORS_FAIL = 'ADMIN_LOAD_DONORS_FAIL';

export const ADMIN_LOAD_DONATIONS = 'ADMIN_LOAD_DONATIONS';
export const ADMIN_LOAD_DONATIONS_SUCCESS = 'ADMIN_LOAD_DONATIONS_SUCCESS';
export const ADMIN_LOAD_DONATIONS_FAIL = 'ADMIN_LOAD_DONATIONS_FAIL';

export const ADMIN_LOAD_LOCATIONS = 'ADMIN_LOAD_LOCATIONS';
export const ADMIN_LOAD_LOCATIONS_SUCCESS = 'ADMIN_LOAD_LOCATIONS_SUCCESS';
export const ADMIN_LOAD_LOCATIONS_FAIL = 'ADMIN_LOAD_LOCATIONS_FAI';

export const ADMIN_SEND_EMAIL_REMINDERS = 'ADMIN_SEND_EMAIL_REMINDERS';
export const ADMIN_SEND_EMAIL_REMINDERS_SUCCESS = 'ADMIN_SEND_EMAIL_REMINDERS_SUCCESS';
export const ADMIN_SEND_EMAIL_REMINDERS_FAIL = 'ADMIN_SEND_EMAIL_REMINDERS_FAIL';

export const VALIDATE_TOKEN = 'VALIDATE_TOKEN';
export const VALIDATE_TOKEN_SUCCESS = 'VALIDATE_TOKEN_SUCCESS';
export const VALIDATE_TOKEN_FAIL = 'VALIDATE_TOKEN_FAIL';

export const GET_LOCATION = 'GET_LOCATION';
export const GET_LOCATION_SUCCESS = 'GET_LOCATION_SUCCESS';
export const GET_LOCATION_FAIL = 'GET_LOCATION_FAIL';

export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const UPDATE_LOCATION_SUCCESS = 'UPDATE_LOCATION_SUCCESS';
export const UPDATE_LOCATION_FAIL = 'UPDATE_LOCATION_FAIL';

export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';

export const NEW_PASSWORD = 'NEW_PASSWORD';
export const NEW_PASSWORD_SUCCESS = 'NEW_PASSWORD_SUCCESS';
export const NEW_PASSWORD_FAIL = 'NEW_PASSWORD_FAIL';

export const CONFIRM_DONATION = 'CONFIRM_DONATION';
export const CONFIRM_DONATION_SUCCESS = 'CONFIRM_DONATION_SUCCESS';
export const CONFIRM_DONATION_FAIL = 'CONFIRM_DONATION_FAIL';

// Temp hard coded variable until we integrate properly with back end
export const PICKUP_TIME = 'Thursdays from 9 till noon';
